apps/pensiondata/urls.py
from django.conf.urls import url

from .views import edit_plan_annual_attr, delete_plan_annual_attr, add_plan_annual_attr, save_checklist, \
    edit_gov_annual_attr, delete_gov_annual_attr, add_gov_annual_attr, plan_calculated_status, \
    get_calculated_task_status, api_map_contribs, api_map_liabilities, api_map_search, api_chart_contribs, \
    api_chart_list, api_chart_data

app_name = 'pensiondata'

urlpatterns = [

    url(r'^plan_annual_attr/edit/$', edit_plan_annual_attr, name = "edit_plan_annual_attr"),
    url(r'^plan_annual_attr/delete/$', delete_plan_annual_attr, name = "delete_plan_annual_attr"),
    url(r'^plan_annual_attr/add/$', add_plan_annual_attr, name = 'add_plan_annual_attr'),

    url(r'^gov_annual_attr/edit/$', edit_gov_annual_attr, name = "edit_gov_annual_attr"),
    url(r'^gov_annual_attr/delete/$', delete_gov_annual_attr, name = "delete_gov_annual_attr"),
    url(r'^gov_annual_attr/add/$', add_gov_annual_attr, name = 'add_gov_annual_attr'),

    url(r'^save_checklist/$', save_checklist, name = 'save_checklist'),
    url(r'^plan_calculated_status/$', plan_calculated_status, name = 'plan_calculated_status'),
    url(r'^get_calculated_task_status/$', get_calculated_task_status, name = 'get_calculated_task_status'),

    url(r'^api/map/search/(?P<state>[A-Za-z]{2})/$', api_map_search, name = 'api_map_search'),
    url(r'^api/map/contribs/(?P<state>[A-Za-z]{2})/$', api_map_contribs, name = 'api_map_contribs'),
    url(r'^api/map/liabilities/(?P<state>[A-Za-z]{2})/$', api_map_liabilities, name = 'api_map_liabilities'),
    url(r'^api/charts/$', api_chart_list, name = 'api_chart_list'),
    url(r'^api/chart/contribs/(?P<government_id>\d+)/$', api_chart_contribs, name = 'api_chart_contribs'),
    url(r'^api/chart/(?P<query>\w+)/(?P<government_id>\d+)/$', api_chart_data, name = 'api_chart_data'),

]

urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from pensiondata.views import HomeView, PlanListView, PlanDetailView, export_file, GovernmentDetailView, generate_reporting_table

admin.autodiscover()

urlpatterns = [
    url(r'^', include('common.urls')),
    url(r'^$',  PlanListView.as_view(), name='home'),
    url(r'^pension/', include('pensiondata.urls')),
    url(r'^plan-detail/(?P<PlanID>\d+)$', PlanDetailView.as_view(), name='plan-detail'),
    url(r'^government-detail/(?P<GovernmentID>\d+)$', GovernmentDetailView.as_view(), name='government-detail'),
    url(r'^plan-detail/ExportFile$', export_file),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^generate_reporting_table/$', generate_reporting_table, name='generate_reporting_table'),
]

urlpatterns += [url(r'^nested_admin/', include('nested_admin.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/pensiondata/models.py
#########################################################################################################

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

# @formatter:off
from __future__ import unicode_literals

from django.db import connection, models
from django.core.validators import MaxValueValidator, MinValueValidator
import re
import datetime, decimal
#########################################################################################################

ATTRIBUTE_TYPE_CHOICES = (
    ('static', 'static'),
    ('calculated', 'calculated'),
)

PRESENTATIONS_EXROPT_CHOICES = (
    ('xlsx', 'xlsx'),
)

ATTRIBUTE_DATATYPES_CHOICES = (
    ('real', 'real'),
    ('int', 'int'),
    ('int_separated3', 'int_separated3'),
    ('text', 'text'),
    ('percentage', 'percentage'),
    ('percentage2', 'percentage2'),
    ('percentage4', 'percentage4'),
    ('yesno', 'yesno'),
    ('shortdate', 'shortdate')

)

SORTED_ATTRIBUTE_DATATYPES_CHOICES = sorted(
    ATTRIBUTE_DATATYPES_CHOICES, key=lambda x: x[1]
)

CALCULATED_STATUS_CHOICES = (
    ('in progress', 'in progress'),
    ('done', 'done')
)


class County(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255)
    retirement_census_county_code = models.CharField(max_length=3, null=True, blank=True)
    retirement_census_state_code = models.CharField(max_length=2, null=True, blank=True)
    state = models.ForeignKey('State', models.DO_NOTHING, null=True, blank=True)

    class Meta:
        db_table = 'county'
        verbose_name_plural = 'Counties'

    def __str__(self):
        return self.name


class DataSource(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255, unique=True)
    trust_level = models.IntegerField()
    private = models.BooleanField(default=False, blank=True)

    class Meta:
        managed = True
        db_table = 'data_source'
        verbose_name = 'Data Source'
        verbose_name_plural = 'Data Sources'
        ordering = ('trust_level',)

    def __str__(self):
        return self.name

    @property
    def is_master_source(self):
        return self.id == 0  # NOTE: hardcodes


class AttributeCategory(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=256)

    class Meta:
        managed = True
        verbose_name = 'Attribute Category'
        verbose_name_plural = 'Attribute Categories'
        db_table = 'attribute_category'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Government(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255)
    state = models.ForeignKey('State', models.DO_NOTHING, null=True, blank=True)
    government_type = models.ForeignKey('GovernmentType', models.DO_NOTHING, null=True, blank=True)
    county = models.ForeignKey('County', models.DO_NOTHING, null=True, blank=True)
    latitude = models.DecimalField(max_digits=12, decimal_places=8, blank=True, null=True)
    longitude = models.DecimalField(max_digits=12, decimal_places=8, blank=True, null=True)

    class Meta:
        db_table = 'government'
        verbose_name = 'Government'
        verbose_name_plural = 'Governments'

    def __str__(self):
        return "%s" % self.name


class GovernmentAttribute(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=256, null=True, blank=True)
    data_source = models.ForeignKey('DataSource', models.DO_NOTHING, blank=True, null=True)
    datatype = models.CharField(max_length=256, choices=SORTED_ATTRIBUTE_DATATYPES_CHOICES, null=True, blank=True)
    attribute_category = models.ForeignKey('AttributeCategory', models.DO_NOTHING, blank=True, null=True)
    line_item_code = models.CharField(max_length=256, null=True, blank=True)
    display_order = models.IntegerField(null=True, blank=True)
    attribute_column_name = models.CharField(max_length=256, null=True, blank=True)
    multiplier = models.DecimalField(max_digits=30, decimal_places=6, null=True, blank=True, default=1000)
    weight = models.IntegerField(null=True, blank=True, default=0)

    # master attribute
    attributes_for_master = models.CharField('Source Attributes', max_length=256,
                                             null=True, blank=True,
                                             help_text='Source Attributes for the master attribute')

    # properties for value
    attribute_type = models.CharField(max_length=16, choices=ATTRIBUTE_TYPE_CHOICES, default='static')
    calculated_rule = models.TextField(null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'government_attribute'
        verbose_name = 'Government Attribute'
        verbose_name_plural = 'Government Attributes'
        unique_together = (('data_source', 'line_item_code'),)

    @property
    def is_static(self):
        return self.attribute_type == 'static'

    @property
    def category(self):
        if self.attribute_category is None:
            return ''
        return self.attribute_category.name

    @property
    def is_master_attribute(self):
        return self.data_source.is_master_source

    def __str__(self):
        return self.name


class GovernmentAttrSummary(models.Model):
    """
    This is a View in DB
    NOTE: readonly
    """
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=256, null=True, blank=True)
    datatype = models.CharField(max_length=256, null=True, blank=True)
    line_item_code = models.CharField(max_length=256, null=True, blank=True)
    display_order = models.IntegerField(null=True, blank=True)
    attribute_column_name = models.CharField(max_length=256, null=True, blank=True)
    multiplier = models.DecimalField(max_digits=30, decimal_places=6, null=True, blank=True, default=1000)
    weight = models.IntegerField(default=0, null=True, blank=True)
    attributes_for_master = models.CharField('Source Attributes', max_length=256,
                                             null=True, blank=True,
                                             help_text='Source Attributes for the master attribute')

    attribute_type = models.CharField(max_length=16, choices=ATTRIBUTE_TYPE_CHOICES, default='static')
    calculated_rule = models.TextField(null=True, blank=True)

    data_source_id = models.IntegerField()
    attribute_category_id = models.IntegerField()
    data_source_name = models.CharField(max_length=255)
    attribute_category_name = models.CharField(max_length=256)

    class Meta:
        managed = False
        db_table = 'governmentattrview'


class GovernmentAnnualAttribute(models.Model):
    id = models.BigAutoField(primary_key=True)
    government = models.ForeignKey(Government, models.DO_NOTHING, null=True, blank=True)
    year = models.CharField(max_length=4)
    government_attribute = models.ForeignKey('GovernmentAttribute', models.DO_NOTHING, null=True, blank=True, related_name='annual_attrs')
    attribute_value = models.CharField(max_length=256, null=True, blank=True)

    is_from_source = models.NullBooleanField(
        default=None,
        help_text='check if the value is from source or from user just for Master Attribute'
    )

    class Meta:
        unique_together = ('government', 'year', 'government_attribute',)
        db_table = 'government_annual_attribute'
        verbose_name = 'Government Annual Attribute'
        verbose_name_plural = 'Government Annual Attributes'

    def __str__(self):
        return "Government Annual Attribute(%s)" % self.year

    @property
    def data_source(self):
        return self.government_attribute.data_source.name

    @property
    def category(self):
        return self.government_attribute.attribute_category.name

    @property
    def value(self):
        """
        :return: string value
        """
        if self.government_attribute.is_master_attribute and self.is_from_source:
            print('here 1')
            attr_ids_for_master = self.government_attribute.attributes_for_master
            if attr_ids_for_master is None:
                return '0'
            else:
                attr_id_list = attr_ids_for_master.split(",")
                attr_id_list = list(map(int, attr_id_list))

                try:  # NOTE: if it is calculated_rule?
                    print(GovernmentAnnualAttribute.objects.filter(government=self.government, year=self.year,
                                                             government_attribute__id__in=attr_id_list))
                    obj = GovernmentAnnualAttribute.objects.filter(government=self.government, year=self.year,
                                                                   government_attribute__id__in=attr_id_list). \
                        order_by('-government_attribute__weight')[0]
                    return obj.attribute_value
                except Exception as e:
                    print(e.__dict__)
                    return '0'

        if self.government_attribute.is_static:
            return self.attribute_value

        stored_rule = self.government_attribute.calculated_rule
        calculated_rule = ''
        calc_items = re.split(r'#([\+\-\*\/\(\)]|\d+)#', stored_rule)

        for item in calc_items:
            if item == '':
                continue
            if '%' in item:
                static_value = re.findall(r'%(.+)%', item)[0]
                calculated_rule += static_value

templates/about.html
{% extends "base.html" %}

{% block content %}

<h2>{{title}}.</h2>

<p>This is a sample polls application that demonstrates the use of Django web framework.</p>

{% endblock %}

templates/contact.html
{% extends "base.html" %}

{% block content %}

<h2>{{title}}.</h2>

<h3>Support</h3>
<address>
    <strong>Python Tools for Visual Studio:</strong> <a href="http://pytools.codeplex.com/" target="_blank">http://pytools.codeplex.com/</a><br />
</address>

<h3>Links</h3>
<address>
    <strong>Django:</strong> <a href="https://www.djangoproject.com/" target="_blank">https://www.djangoproject.com/</a><br />
    <strong>Microsoft Azure:</strong> <a href="http://azure.microsoft.com/" target="_blank">http://azure.microsoft.com/</a><br />
</address>

{% endblock %}

templates/government_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra-styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/libs/jquery.dataTables.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/libs/colReorder.dataTables.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/libs/fixedColumns.dataTables.min.css' %}" />
{% endblock %}

{% block content %}
<div id="content">
  <!-- Plan Details -->

  <div id="breadcrumbs">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Plans</a></li>
      <li class="breadcrumb-item active">{{ government.display_name }}</li>
    </ol>
  </div>

  <h3>Government Details</h3>
  <table class="table table-hover table-bordered table-striped">
    <tr>
      <td>Name</td><td>{{ government.name }}</td>
    </tr>
    <tr>
      <td>State</td><td><a href="">{{ government.state }}</a></td>
    </tr>
    <tr>
      <td>Type</td><td>{{ government.government_type.level }}</td>
    </tr>

  </table>

  <!-- Plan Annual Attributes -->
  <div class="annual_title">Government Annual Attributes:</div>
  <a class="start-settings" href="#"><i class="fa fa-cog" aria-hidden="true"></i></a>

  <!-- Selector Popup -->
  {% include 'includes/column_selector_popup.html' with datasource_list=datasource_list category_list=category_list full_attr_list=full_attr_list model_name="government" is_admin_page=False %}
  <!-- PlanAnnualAttribute Table -->
  <div class="annual_table_area" style="display:none; overflow: hidden">
    <table class="table table-bordered table-striped" id="table-annual-data">
      <thead>
        <tr class="tr-attribute">
          <th style="vertical-align: middle; width: 45px;">Year</th>
          {% for attr in full_attr_list %}
            {% if attr.selected %}
          <th class="th-attr-{{ attr.attribute_id }} td-source-{{ attr.data_source_id }}"
              data-category-id="{{ attr.category_id }}">
            {{ attr.attribute_name|capfirst }}</th>
            {% endif %}
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for year in year_list %}
            <tr class="tr-annual-data-per-year">
              <td>{{ year.year }}</td>
              {% for attr in full_attr_list %}
                {% if attr.selected %}
                  <td class="td-attr-{{ attr.attribute_id }} td-source-{{ attr.data_source_id }}"
                      id="td-id-{{ year.year }}-{{ attr.attribute_id }}"
                      data-annual-data-pk="-1"
                  ></td>
                {% endif %}
              {% endfor %}
            </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

<!-- Export:
<a href="ExportFile?file_type=csv&plan_id={{ plan.id }}"> CSV </a>
<a href="ExportFile?file_type=json&plan_id={{ plan.id }}"> JSON </a>
<a href="ExportFile?file_type=stata&plan_id={{ plan.id }}"> Stata </a>
<a href="ExportFile?file_type=xlsx&plan_id={{ plan.id }}"> Excel </a>

-->

</div><!-- end of content -->
{% endblock %}

{% block extra-scripts %}
  <script src="{% static 'js/libs/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/libs/dataTables.colReorder.min.js' %}"></script>
  <script src="{% static 'js/libs/dataTables.fixedColumns.min.js' %}"></script>

  <script type="text/javascript">
    console.log('script start');
    var government_annual_data = "{{ government_annual_data }}";
    var save_checklist_url = '{% url "pensiondata:save_checklist" %}';

    // string -> JSON object
    var plan_annual_data = JSON.parse(government_annual_data.replace(/&quot;/g, '"'));

    console.log('JSON parse');

  </script>
  <script type="text/javascript" src="{% static 'js/convert.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/detail_actions.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/annual_table.js' %}"></script>
  <script type="text/javascript">
    var is_government = true;
  </script>
{% endblock %}

templates/plan-detail.html
{% extends "base.html" %}
{% load static %}

{% block extra-styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/libs/jquery.dataTables.min.css' %}" />
{% endblock %}

{% block content %}
<div id="content">
  <!-- Plan Details -->
  
  <div id="breadcrumbs">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Plans</a></li>
      <li class="breadcrumb-item active">{{plan.display_name }}</li>
    </ol>
  </div>

  <h3>Plan Details</h3>
  <table class="table table-hover table-bordered table-striped">
    <tr>
      <td>Census Plan Id</td><td>{{ plan.census_plan_id }}</td>
    </tr>
    <tr>
      <td>Name</td><td>{{ plan.display_name }}</td>
    </tr>
    <tr>
      <td>State</td><td>{{ plan.admin_gov.state }}</td>
    </tr>

  </table>

  <!-- Plan Annual Attributes -->
<h3 style="display: inline">Plan Annual Attributes:</h3>&nbsp;
  <a class="start-settings" href="#"><i class="fa fa-cog" aria-hidden="true"></i></a>

  <!-- Selector Popup -->
  <div class="poup-settings-wrap panel panel-default">
    <div class="poup-settings">
    <form id="column_checklist_form">{% csrf_token %}
      <div class="arrow"></div>
        <div class="panel-body">
        <div class="clearfix">
          <!-- DataSource selector -->
          <div class="pull-left datasource-selector">
            <h4>Data Sources</h4>
            <ul class="list-group column-list datasource-list">
            {% for ds in datasource_list %}
              <li class="datasource-level">
                <label>
                  <input type="checkbox"
                         name="datasource_checked_states[]"
                         class="column-check-box datasource-column"
                         data-source-id="{{ ds.id }}"
                     {% if not request.session.datasource_checked_states or ds.id in request.session.datasource_checked_states %}
                         checked
                     {% endif %}
                         value={{ ds.id }}
                  >{{ ds.name }}</label></li>
            {% endfor %}
            </ul>
          </div>

          <!-- Attribute selector -->
          <div class="pull-left attr-selector">
            <h4>Attributes</h4>
            <input class="form-control input-search" type="text" placeholder="Search...">
            <br>
            <ul class="list-group column-list attr-list">
            {% for category in category_list %}
              <li class="category-level">
                <label>
                  <input type="checkbox"
                         name="category_checked_states[]"
                         class="column-check-box category-column"
                         data-category-id="{{ category.id }}"
                     {% if not request.session.category_checked_states or category.id in request.session.category_checked_states %}
                         checked
                     {% endif %}
                         value={{ category.id }}
                  >{{ category.name }}</label>
                <ul>
                {% for attr in attr_list %}
                  {% if attr.category_id == category.id %}
                    <li class="attr-level">
                      <label>
                        <input type="checkbox"
                               name="attr_checked_states[]"
                               class="column-check-box attr-column"
                               data-attr-id="{{ attr.attribute_id }}"
                               data-source-id="{{ attr.data_source_id }}"
                           {% if not request.session.attr_checked_states or attr.attribute_id in request.session.attr_checked_states %}
                               checked
                           {% endif %}

                           {% if attr.data_source_id not in request.session.datasource_checked_states %}
                               disabled="disabled"
                           {% endif %}

                               value={{ attr.attribute_id }}
                        >{{ attr.attribute_name }}</label></li>
                  {% endif %}
                {% endfor %}
                </ul>
              </li>
            {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="panel-footer clearfix">
  {#          <button type="button" class="btn btn-default pull-left button-default">Default</button>#}
        <button type="button" class="btn btn-success pull-right button-apply">Apply</button>
        <button type="button" class="btn btn-default pull-right button-cancel">Cancel</button>
      </div>
    </form>
    </div>
  </div>

  <!-- PlanAnnualAttribute Table -->
  <div class="annual_table_area" style="display:none;">
    <table class="table table-bordered table-striped" id="table-annual-data">
      <thead>
        <tr class="tr-category"></tr>
        <tr class="tr-attribute">
          {% for attr in attr_list %}
            <th class="th-attr-{{ attr.attribute_id }} td-source-{{ attr.data_source_id }}"
                data-category-id="{{ attr.category_id }}">
              {{ attr.attribute_name|capfirst }}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for year in year_list %}
        <tr class="tr-annual-data-per-year">
          <td>{{ year.year }}</td>
          {% for attr in attr_list %}
          <td class="td-attr-{{ attr.attribute_id }} td-source-{{ attr.data_source_id }}"
              id="td-id-{{ year.year }}-{{ attr.attribute_id }}"
              data-annual-data-pk="-1"
          ></td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


</div><!-- end of content -->
{% endblock %}

{% block extra-scripts %}
  <script src="{% static 'js/libs/jquery.dataTables.min.js' %}"></script>

  <script type="text/javascript">
    var plan_annual_data = "{{ plan_annual_data }}";
    var save_checklist_url = '{% url "pensiondata:save_checklist" %}';

    // string -> JSON object
    plan_annual_data = JSON.parse(plan_annual_data.replace(/&quot;/g, '"'));

  </script>
  <script type="text/javascript" src="{% static 'js/annual_table.js' %}"></script>
{% endblock %}

templates/plan_detail.html
{% extends "base.html" %}
{% load static %}
{% load annual_table_tags %}

{% block extra-styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/libs/jquery.dataTables.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/libs/colReorder.dataTables.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/libs/fixedColumns.dataTables.min.css' %}" />
{% endblock %}

{% block content %}
<div id="content">
  <!-- Plan Details -->

  <div id="breadcrumbs">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Plans</a></li>
      <li class="breadcrumb-item active">{{plan.display_name }}</li>
    </ol>
  </div>

  <h3>Plan Details</h3>
  <table class="table table-hover table-bordered table-striped">
    <tr>
      <td>Census Plan Id</td><td>{{ plan.census_plan_id }}</td>
    </tr>
    <tr>
      <td>Name</td><td>{{ plan.display_name }}</td>
    </tr>
    <tr>
      <td>Administering Government</td><td><a href="/government-detail/{{ plan.admin_gov.id }}">{{ plan.admin_gov.name }}</a></td>
    </tr>

  </table>

  <!-- Plan Annual Attributes -->
  <div class="annual_title">Plan Annual Attributes:</div>
  <a class="start-settings" href="#"><i class="fa fa-cog" aria-hidden="true"></i></a>

  <!-- Selector Popup -->
  {% include 'includes/column_selector_popup.html' with datasource_list=datasource_list category_list=category_list full_attr_list=full_attr_list model_name="plan" is_admin_page=False  %}

  <!-- PlanAnnualAttribute Table -->
  <div class="annual_table_area" style="display:none; overflow: hidden">
    <table class="table table-bordered table-striped" id="table-annual-data">
      <thead>
        <tr class="tr-attribute">
          <th style="vertical-align: middle; width: 45px;">Year</th>
          {% for attr in full_attr_list %}
            {% if attr.selected %}
          <th class="th-attr-{{ attr.attribute_id }} td-source-{{ attr.data_source_id }}"
              data-category-id="{{ attr.category_id }}" data-attr-id="{{ attr.attribute_id }}">
            {{ attr.attribute_name|capfirst }}</th>
            {% endif %}
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for year in year_list %}
        <tr class="tr-annual-data-per-year">
          <td>{{ year.year }}</td>
          {% for attr in full_attr_list %}
            {% if attr.selected %}
          <td class="td-attr-{{ attr.attribute_id }} td-source-{{ attr.data_source_id }}"
              id="td-id-{{ year.year }}-{{ attr.attribute_id }}"
              data-annual-data-pk="-1"
          ></td>
            {% endif %}
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

Export:

<a href="{% build_export_url 'csv' plan.id year_from year_to %}" class="export-file-link"> CSV </a>
<a href="{% build_export_url 'json' plan.id year_from year_to %}" class="export-file-link"> JSON </a>
<a href="{% build_export_url 'stata' plan.id year_from year_to %}" class="export-file-link"> Stata </a>
<a href="{% build_export_url 'xlsx' plan.id year_from year_to %}" class="export-file-link"> Excel </a>
| <label><input id="exportFile" type="checkbox" checked value="all"> All fields</label>

<br/>
Presentations export:

{% for export in presentations_exports %}
    <a href="{% build_export_url export.export_type plan.id year_from year_to export.name %}" class="export-file-link"> {{ export.name }} </a>
{% endfor %}

</div><!-- end of content -->
{% endblock %}

{% block extra-scripts %}
  <script src="{% static 'js/libs/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/libs/dataTables.colReorder.min.js' %}"></script>
  <script src="{% static 'js/libs/dataTables.fixedColumns.min.js' %}"></script>

  <script type="text/javascript">
    console.log('script start');
    var plan_annual_data = "{{ plan_annual_data }}";
    var save_checklist_url = '{% url "pensiondata:save_checklist" %}';

    // string -> JSON object
    plan_annual_data = JSON.parse(plan_annual_data.replace(/&quot;/g, '"'));

    console.log('JSON parse');

  </script>
  <script type="text/javascript" src="{% static 'js/convert.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/detail_actions.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/annual_table.js' %}"></script>
{% endblock %}